### ISSUE TITLE
A bad perfomance: EvolveAllGivenPokemons

### ISSUE THREAD

**Issue by Albeoris** [shiftcodeYT/PokeBot3#10]
```
foreach (var pokemon in pokemonToEvolve) // 300 in a my case
evolvePokemonOutProto = await client.EvolvePokemon(pokemon.Id); // 1 second
await Task.Delay(3000); // 3 second

```
(300 * (3+1) / 60) = 20 minutes
Filter pokemons before evolve. Check what it can evolute and player has resources.

Also there is no progress and an application looks hanging.
And thank you for the hard work! (:

**Comment by shiftcodeYT** [comment]
You're right :P I'll look into it tomorrow.

On Fri, Jul 22, 2016 at 22:42, Albeoris <notifications@github.com> wrote:
foreach (var pokemon in pokemonToEvolve) // 300 in a my case
evolvePokemonOutProto = await client.EvolvePokemon(pokemon.Id); // 1 second
await Task.Delay(3000); // 3 second



(300 * (3+1) / 60) = 20 minutes
Filter pokemons before evolve. Check what it can evolute and player has resources.

Also there is no progress and an application looks hanging.
And thank you for the hard work! (:

**Comment by shiftcodeYT** [comment]
Done in 3.0
