### ISSUE TITLE
Google is asking password in Android phone after using bot

### ISSUE THREAD

**Issue by tunayuyar** [shiftcodeYT/PokeBot3#100]
I'm not 100% sure it is about your bot but after started using it last night, google asked password in my phone saying there is change in your google account we need to verify your password. 

It asked 1 time after started using it, and I entered password, continued using it and closed bot went to bed. This morning I saw that exclamtion mark warning again asking my password.

Is it possible for you to check this? 

Thanks for the good work.

**Comment by shiftcodeYT** [comment]
TBH, i have no idea. Did you run the bot on your computer at home or on a server?

**Comment by tunayuyar** [comment]
At home, I did run bot again today couple of hours ago, so far no problems. 

I can try on my dedicated server too.

**Comment by tunayuyar** [comment]
Also I should add, I was running other bot(python codded one at github) on my server which is not in my country, on the day before yesterday. 

I changed to your bot  on yesterday night as i mention.

**Comment by shiftcodeYT** [comment]
It's probably just google security that kicked in. As long as the bot works, it's probably fine. If this happens again, open a new issue and link to this one(#100)

**Comment by tunayuyar** [comment]
Reporting in:

Probably google does that when ip changes with bot. Today tried bot at my office and my android phone was asking password again. So I suppose nothing to worry about.

**Comment by shiftcodeYT** [comment]
@tunayuyar Yup, probably that's the reason.
