### ISSUE TITLE
Feature Request - Always transfer

### ISSUE THREAD

**Issue by Blurline** [shiftcodeYT/PokeBot3#103]
Perfect job bot 3  thx

Just one Feature:

Always transfer list -> Pidgeotto to expensive to evolve.....

**Comment by shiftcodeYT** [comment]
What do you mean?

**Comment by Blurline** [comment]
In the new gui, there are 3 list for pokemon.
No catch/no transfer/envolve

I missing a 4th -> always transfer - > catch it an get the bonbon but after an envolve they are useless like pidgeotto (expensiv 50bonbon)

5th -> never envolve -> i want to envolve it myself -> each of them have different attacke, take al look at your zulbat -> different combat attack.


To envolve a pidgeotto

**Comment by shiftcodeYT** [comment]
aah ok :) I'll look into it

**Comment by Blurline** [comment]
another example 

i got 500 pidgey candy, but say dont evolve pidgeotto and transfer pidgeotto is false, but "dont transfer evolve able" is true -> pidgetto isnt transfered

**Comment by shiftcodeYT** [comment]
Done :)
