### ISSUE TITLE
We can't find any pokestops

### ISSUE THREAD

**Issue by alex8998** [shiftcodeYT/PokeBot3#108]
Hi,

I've set the bot (basically change to the 6 spot at Minneapolis). But it seems not working. I can't catch Pokémon or Pokestop. Did I forget something ?

Thanks

![pokemon](https://cloud.githubusercontent.com/assets/20769798/17290258/e83600b4-57dd-11e6-876e-cb1e89d21a9a.PNG)

**Comment by shiftcodeYT** [comment]
@alex8998 Can you send me a screenshot of your config?

**Comment by alex8998** [comment]
Yes of course
![pokemon2](https://cloud.githubusercontent.com/assets/20769798/17290527/24bfb1fa-57df-11e6-8676-3598bbce3492.PNG)

**Comment by shiftcodeYT** [comment]
@alex8998 Try this (with dots instead of comma): 
45.030060
-93.319229

**Comment by shiftcodeYT** [comment]
And with more detail

**Comment by alex8998** [comment]
Perfect with dots ! Thanks :)
Last question, is it normal the line with the distance ? I've set the location at Minneapolis and i checked, my character is on this spot.

**Comment by shiftcodeYT** [comment]
@alex8998 Lol what did you do? 100000 seconds?

**Comment by alex8998** [comment]
Nothing special. When I check on Nox, I'm in Minneapolis.

![pokemon4](https://cloud.githubusercontent.com/assets/20769798/17291120/5afc6148-57e2-11e6-9a23-88c51fce9475.PNG)

**Comment by shiftcodeYT** [comment]
@alex8998 Try to close all bot windows, delete the config folder, close all pokemon go apps and try again. This is weird.

**Comment by conmcgu** [comment]
I had this problem I just changed location with he map it worked fine for me

**Comment by shiftcodeYT** [comment]
@conmcgu Right, altitude was on 0

**Comment by alex8998** [comment]
Alright. Configs folder deleted and seems ok now :)

**Comment by shiftcodeYT** [comment]
@alex8998 Great!

**Comment by alex8998** [comment]
Thanks you !

**Comment by shiftcodeYT** [comment]
@alex8998 No Problem!
