### ISSUE TITLE
Pokestops not loading 

### ISSUE THREAD

**Issue by saifownzu** [shiftcodeYT/PokeBot3#109]
I keep getting this despite being in the central park still.

[14:50:29] We cant find any PokeStops in a range of 5000m!
[14:50:30] We cant find any PokeStops, which are unused! Probably Server unstable, or you visted them all. Retrying..

I realized it was really odd I ran out of all pokeballs I had till I saw  it was not visiting pokestops at all

**Comment by shiftcodeYT** [comment]
@saifownzu In location map, drag it around a few meters and click set.(to set altitude, it cant find pokestops 300m under earth)

**Comment by saifownzu** [comment]
@shiftcodeYT , I have already tried that. the altitude is like 16. something, even on default location its giving me the same error.

**Comment by saifownzu** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19819573/17293593/e8826c6c-57f9-11e6-9143-a2cb83dcae90.png)
Here's a couple of screenies of settings n stuff 
![capture](https://cloud.githubusercontent.com/assets/19819573/17293625/207c0844-57fa-11e6-8b90-fad2ccc573d0.PNG)

**Comment by shiftcodeYT** [comment]
@saifownzu altitude is on 0

**Comment by saifownzu** [comment]
@shiftcodeYT it's on default "Set Location" anyways, after using "Select All" on Don't Catch, it seems to find pokestops now.

**Comment by shiftcodeYT** [comment]
@saifownzu so it works again now?

**Comment by saifownzu** [comment]
@shiftcodeYT yes, I can farm with catching off. :+1:

**Comment by shiftcodeYT** [comment]
@saifownzu then try turning it on again. 😀

**Comment by saifownzu** [comment]
okay, btw since pokevision is down. are you going to implement self-account scanning?

**Comment by shiftcodeYT** [comment]
@saifownzu What do u mean

**Comment by saifownzu** [comment]
@shiftcodeYT , Pokevision was shutdown due to niantic complaining n stuff, but a couple of developers made Self scanners where u can scan surrounding pokemons using your account itself.
take a look @ https://www.reddit.com/r/pokescanner

**Comment by shiftcodeYT** [comment]
@saifownzu Thanks for notifying me!

**Comment by saifownzu** [comment]
@shiftcodeYT no problem :) , glad I can try to support you work

**Comment by saifownzu** [comment]
pokestops stopped finding now even with the catch on/off. loc was changed around a couple of metres still unfixed, tried deleting configs n stuff but still persisting.

**Comment by shiftcodeYT** [comment]
@saifownzu That's odd. It still works for me. Try switching around dot and comma in the coords.

**Comment by saifownzu** [comment]
@shiftcodeYT nope still persistent

**Comment by shiftcodeYT** [comment]
@saifownzu Thats really odd. I'll try to help in an hour or so. On my phone ATM

**Comment by saifownzu** [comment]
@shiftcodeYT alright, take your time

**Comment by shiftcodeYT** [comment]
Ok then, back on PC:
1) Send me your system config(OS, etc)
2) Try to redownload current release and run it, ONLY enter your account details & change nothing else, click save and close the bot after 3-5 seconds
3) if you still dont have a "Config" Directory, try the same thing again but run it as administrator.

Hope we can fix this, ShiftCode

**Comment by shiftcodeYT** [comment]
Fuck, wrong issue.

**Comment by shiftcodeYT** [comment]
Try to redownload current release, and make a new folder to unzip it in. Also try running as admin.
Also, if that doesn't work, send me your system config(OS, etc)

**Comment by shiftcodeYT** [comment]
@shiftcodeYT test

**Comment by saifownzu** [comment]
@shiftcodeYT  ehhh none worked, it's a Win 10 x64 
4Gigs , i7 2600k, gtx 550 ti but i dont think its a windows issue, as its the same thing at my other pc with different network and different account.
Other PC is Win 8.1 x86 3Gigs Core 2 duo 1.6ghz gt 610

**Comment by shiftcodeYT** [comment]
@saifownzu can you send me coordinates you are using?

**Comment by saifownzu** [comment]
@shiftcodeYT  40.764883 -73.972967 15.173855

**Comment by shiftcodeYT** [comment]
@saifownzu seems OK. TBH I'm out of ideas.

**Comment by saifownzu** [comment]
@shiftcodeYT i'm on my way home right now, ill see what happens from home connection

**Comment by shiftcodeYT** [comment]
@saifownzu ok

**Comment by sidg2681** [comment]
try putting altitude as zero and leave latitude and longitude as it is
oh and  btw i ve been using the git hub python version of pokevision for a while now but even that seems to have slowed down by a lot recently
not sure if niantic reduced the number of calls u can make or something
but its definetly slower to scan now

**Comment by shiftcodeYT** [comment]
@sidg2681 ok

**Comment by saifownzu** [comment]
I am at home now, I was getting the same error however I tried logging on my main account and it worked normally. Idk what seems to be the issue anymore

**Comment by shiftcodeYT** [comment]
@saifownzu lol that is weird af

**Comment by saifownzu** [comment]
@shiftcodeYT and its back at it again. lol ffs

**Comment by shiftcodeYT** [comment]
@saifownzu wtf is it doing?

**Comment by saifownzu** [comment]
Idek, I even increased range to 50k metres
and it found one within 500m.

**Comment by saifownzu** [comment]
it seems to work with latitude set to 0 for a while then it breaks and latitude goesup somehow

**Comment by shiftcodeYT** [comment]
@saifownzu dafuq

**Comment by saifownzu** [comment]
@shiftcodeYT yeah pretty glitchy somehow, anyways how do I set this up on a CentOS machine? might have it bot on my rdp :3

**Comment by shiftcodeYT** [comment]
@saifownzu only windows for now. Try mono or wine and check if it works.

**Comment by saifownzu** [comment]
alrightie, thank you

**Comment by shiftcodeYT** [comment]
@saifownzu np

**Comment by saifownzu** [comment]
@shiftcodeYT https://www.reddit.com/r/pokemongodev/comments/4vl6sl/getmapobjects_changes_made_in_niantic_update/ take a look at this

**Comment by shiftcodeYT** [comment]
@saifownzu As far as I understand, everything should still work.
