### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by conmcgu** [shiftcodeYT/PokeBot3#110]
Just a quick question bot has been working great which is all good so thanks been levelling me up good, just wanted to ask anyway to save settings so that everytime it loads I don't have to reenter everything, and also if when the bot is running can i still open the app because I'm not with my bot so didn't want to run the app and the bot crash thanks :)

**Comment by shiftcodeYT** [comment]
@conmcgu 1) it saves settings automatically
2) you'd be in 2 locations at the same time. Soft ban guaranteed

**Comment by conmcgu** [comment]
My settings don't save, as in every time I load the bot I have to enter what I want to evolve and transfer (just time consuming) not much bother,and 2) yeah thought as much that's not worries

**Comment by saifownzu** [comment]
@conmcgu are you running the tool using sandboxie? do you have deepfreeze installed?

**Comment by conmcgu** [comment]
Don't have either of them installed they good for running it ?

**Comment by shiftcodeYT** [comment]
@saifownzu Then I have no idea. Is there a config folder?

**Comment by conmcgu** [comment]
Not that ive seen

**Comment by shiftcodeYT** [comment]
Ok then, back on PC:
1) Send me your system config(OS, etc)
2) Try to redownload current release and run it, ONLY enter your account details & change nothing else, click save and close the bot after 3-5 seconds
3) if you still dont have a "Config" Directory, try the same thing again but run it as administrator.

Hope we can fix this, ShiftCode

**Comment by saifownzu** [comment]
@conmcgu nope, I was wondering because these are intended for temporary uses where all data is lost after u close app

**Comment by shiftcodeYT** [comment]
@conmcgu did it help?

**Comment by conmcgu** [comment]
Haven't been back to try yet sounds all good though thanks
