### ISSUE TITLE
Bug Export Player Infos and all Pokemons to CSV not possible. File seems be in use!

### ISSUE THREAD

**Issue by Mamutebr** [shiftcodeYT/PokeBot3#115]
Export Player Infos and all Pokemons to CSV not possible. File seems be in use!
[19:01:03] Exception: System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em PokemonGo.RocketAPI.Logic.Inventory.<GetPlayerStats>d__11.MoveNext() na C:\Users\simon\Documents\GitHub\PokeBot3_Hub\PokemonGo.RocketAPI.Logic\Inventory.cs:linha 87
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PokemonGo.RocketAPI.Logic.Inventory.<ExportPokemonToCSV>d__14.MoveNext() na C:\Users\simon\Documents\GitHub\PokeBot3_Hub\PokemonGo.RocketAPI.Logic\Inventory.cs:linha 187
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() na C:\Users\simon\Documents\GitHub\PokeBot3_Hub\PokemonGo.RocketAPI.Logic\Logic.cs:linha 130
[19:01:03] Starting again.. But waiting 10 Seconds..

**Comment by shiftcodeYT** [comment]
Check your task manager for Pokemongo.something

**Comment by Mamutebr** [comment]
![teste](https://cloud.githubusercontent.com/assets/20781412/17363851/42fc875e-5953-11e6-8143-9a1bdaa9465b.png)

**Comment by shiftcodeYT** [comment]
@Mamutebr close them

**Comment by shiftcodeYT** [comment]
Should be fixed now.
