### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by liuhx9988** [shiftcodeYT/PokeBot3#116]
http://i.imgur.com/x3I40EP.png
It just keeping showing this again and again

**Comment by WhiteShadow7** [comment]
I Have the same Problem on my Virtual Machine :/

**Comment by shiftcodeYT** [comment]
Is it on azure?

**Comment by AzureACW** [comment]
#114 :)

**Comment by shiftcodeYT** [comment]
Azure and other companies were IPblocked by niantic. #114
