### ISSUE TITLE
Suggestion : log.txt

### ISSUE THREAD

**Issue by ilikesomething** [shiftcodeYT/PokeBot3#12]
It would be very nice to get the logs from the console also in a .txt :)

**Comment by shiftcodeYT** [comment]
Well, you could run the program from cmd: "x.exe >> log.txt", but that disables output in console. I'll look into it tomorrow.

**Comment by ilikesomething** [comment]
yes it would be better to have both :) thank you anyway!

**Comment by blindreaper** [comment]
Perhaps hold off reinventing the wheel

`PokemonGo.RocketAPI.Console.exe 2>&1 | tee log.txt`

**Comment by ilikesomething** [comment]
work as excepted thanks !!

**Comment by houmik** [comment]
Hi you did a really great job with 3.0 and i want thank you for your work. 

I have also new feature request. I saw u using PokeVision and your bot know where is pokestops and pokemons. Can you add something like Pokemon priority list ? When Bot see pokemon on this list, its going to ignore everything ( Pokestops or pokemons in range ) and just go to catch the one with priority, It will be really great for catching Dratini, Snorlax or other rare pokemons.

Sorry for my bad English :)
