### ISSUE TITLE
PokemonGo Servers offline

### ISSUE THREAD

**Issue by itskaje** [shiftcodeYT/PokeBot3#122]
it says pokemon go servers are offline when in fact it is online as im able to log in on my phone.
whats going on?

**Comment by DoctorShodan** [comment]
Same problem here, no idea where the problem might come from.

**Comment by DirtbikeKing247** [comment]
Same issue 
![pkm_error](https://cloud.githubusercontent.com/assets/14851882/17381103/4c7193d4-5998-11e6-9789-a0c238a0940d.png)
