### ISSUE TITLE
cant find any pokestops

### ISSUE THREAD

**Issue by BoBadas231** [shiftcodeYT/PokeBot3#126]
This just came with the recent update of pokemon go. me and my friend both have this bug and none of us are soft banned. Gyazo screenshot of the error https://gyazo.com/a384d0100c861d1b189661672454dc6f
Has been saying that for around 2 days. anyone else with the same problem? and yes we have tried multiple locations

**Comment by itskaje** [comment]
Swiftcode said he's working on it and will update us about it tomorrow.

**Comment by Alonalon7** [comment]
ok.. thank's..
cause i had same problem like that.
