### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HelloItsRien** [shiftcodeYT/PokeBot3#128]
Hey!

I have a farm server for my accounts, and after a hour of 5 I got this weird error.
-> https://gyazo.com/2f7eb04f86d7ddcc28ebad447e0c7cd1

Normally I would go and look for myself, but I only code Java and PHP :-)

**Comment by shiftcodeYT** [comment]
@HelloItsRien Right now, every bot is broken, because niantic updated the API. We are working on it. Also, you are probably using a hosting service that got blocked by niantic, like azure.

**Comment by HelloItsRien** [comment]
Nope, I'm using a private home server.
I have a Dell Poweredge R210 at my place ;-)
