### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by FilyaGG** [shiftcodeYT/PokeBot3#132]
Updated the bot on 3.1.3, but the problem remained in the plan poket stops. Maybe I have something wrong?

**Comment by shiftcodeYT** [comment]
@FilyaGG can you PLEASE read readme.md? https://github.com/shiftcodeYT/PokeBot3/blob/master/README.md

**Comment by FilyaGG** [comment]
Sorry have not seen. Thank you.
