### ISSUE TITLE
Diffrent Version when download

### ISSUE THREAD

**Issue by chospirit** [shiftcodeYT/PokeBot3#136]
why when i download 
![image](https://cloud.githubusercontent.com/assets/20858062/17434689/12e0abba-5b36-11e6-92db-b350a4e63aa5.png)

but when i start it was 
![image](https://cloud.githubusercontent.com/assets/20858062/17434699/2e5123de-5b36-11e6-923c-6ac1bb3d2152.png)

**Comment by chospirit** [comment]
Did any one have same problem? or it was just me?

**Comment by rsman17** [comment]
I have the same problem

Dne 5. 8. 2016 13:25 napsal uživatel "chospirit" <notifications@github.com>:

**Comment by jedi2003** [comment]
I have same problem !!

**Comment by clone1084** [comment]
3.2.7 is the last commit but is not the last compiled program that you have downloaded.
You have to wait for the official fixed release.
Please wait and stop asking for the new release until it's fixed. If you keep on asking the work can only be slower.

**Comment by AzureACW** [comment]
From the readme:

Furthermore, I added autoBuild. Please check notes before downloading, as there may be many releases before it's fixed due to autoBuild.

**Comment by FallenDev** [comment]
You "people" realize it's broken right? Whatever you download will not work, why are you even trying? Wait until we fix it. Thank you :)
