### ISSUE TITLE
New Bot?

### ISSUE THREAD

**Issue by Keazy** [shiftcodeYT/PokeBot3#139]
I updated the bot but when I try to use it. It doesn't work. And I know the guys finished finding the API last night. So just wondering is there anything I need to do to find out how to make it work again? Or anything I need to download?

**Comment by shiftcodeYT** [comment]
@Keazy It has to be implemented. Nothing fixes it by itself

**Comment by FallenDev** [comment]
Currently the bot is not working. We are remaking a new GUI for the new API that was released.
