### ISSUE TITLE
Not really an Issue but, here

### ISSUE THREAD

**Issue by saifownzu** [shiftcodeYT/PokeBot3#141]
You can get your API done using this thread I guess
https://www.reddit.com/r/pokemongodev/comments/4trjum/pok%C3%A9mon_go_development_archive_works_in_progress/

since its updated

**Comment by saifownzu** [comment]
also 
https://github.com/keyphact/pgoapi

**Comment by C3rberus9** [comment]
As I understood the API is already ok, they just build a new GUI around it with some new features...

I'm really excited about it...
