### ISSUE TITLE
Can I change the item recycling min?

### ISSUE THREAD

**Issue by ZivC12** [shiftcodeYT/PokeBot3#15]
rn the bot recycles all potion, and keep of max of 20 pokeballs, would love if I had the option to change it (Tried to change the recycle interval but it still recycle every time i start the program or it cant find anyhting close)

**Comment by ilikesomething** [comment]
you can change the interval but like you said when you start it recycle, it would be nice to be able to disable the function

**Comment by spot88** [comment]
Can be changed in settings.cs 
ICollection<KeyValuePair<ItemId, int>> ISettings.ItemRecycleFilter

**Comment by Albeoris** [comment]
Hardcoded. Need move to the external config file.

**Comment by spot88** [comment]
new KeyValuePair<ItemId, int>(ItemId.ItemPokeBall, 20),

**Comment by Alienater** [comment]
Yes, being able to configure how many of each item you want to keep would be very nice. This way you can have the bot farm pokestops/balls and when you go out in the real world you can use your pokeballs and have fun. 

Also as you get more storage space, the default values may not be optimal for you too. 

Best

**Comment by shiftcodeYT** [comment]
Done in 3.0
