### ISSUE TITLE
Change EvolveAllGivenPokemons to minimum number, add LuckyEgg option

### ISSUE THREAD

**Issue by blindreaper** [shiftcodeYT/PokeBot3#19]
So minimum of 1 = current mode, evolves when you have at least one of the pokemon.
0 = disabled.

Minimum of 70 will farm pidgeys until you have 840 candies and 70 pidgeys to evolve.  
The 70 pokemon can be made up of any combination of pokemon ready to evolve (69 pidgey, 1 ratata).
It will then activate a lucky egg (if set to true) and then go on an evolving spree.

This will allow you to get double exp evolving pokemon for the full 30 minute duration.

**Comment by shiftcodeYT** [comment]
Done in 3.0
