### ISSUE TITLE
Throw different balls according to rarity

### ISSUE THREAD

**Issue by Hidan123** [shiftcodeYT/PokeBot3#22]
Hey man im lvl 23right now and its struggle :D to farm pidgays,ratatas, etc its only using normal pokeballs on them even they are like 200-400cp could u change it so it will use atleast greatball on pokemon with higher than 200+ cp? or navigate how to do it :D?

**Comment by shiftcodeYT** [comment]
Added as enhancement:
- Detect rarity of a pokemon, throw balls accordingly

**Comment by shiftcodeYT** [comment]
Fixed in 3.0
