### ISSUE TITLE
Suggestion : current lat/long (gps coords)

### ISSUE THREAD

**Issue by ilikesomething** [shiftcodeYT/PokeBot3#26]
It would be nice to log (in the caption of the window ?) the current GPS location (long/lat).

It would allow us to use theses info in case we have to relog.

It would be also nice that when the bot relog automatically (it happens sometimes) that he use the last GPS coord (instead of the .config one), to prevent soft ban

**Comment by shiftcodeYT** [comment]
1) that was in my previous version, i'll gladly readd it ;)

2) that shouldn't be necessary but i'll implement it anyways. :)

**Comment by ilikesomething** [comment]
great ! thanks again

**Comment by shiftcodeYT** [comment]
Done in 3.0
