### ISSUE TITLE
Doduo Doesnt Transfer

### ISSUE THREAD

**Issue by plum04** [shiftcodeYT/PokeBot3#41]
Same as the title, it appears not to transfer doduos
Also it appears the my electabuzz also doesnt get transferred (I have 30 in my inventory :( )

**Comment by plum04** [comment]
http://puu.sh/qch2W/e72e439328.png 
Catches 3 electabuzz's doesnt transfer any

**Comment by Epsilith** [comment]
I'm having the same problem with NidoranFemale
The console outputs:
`[19:23:52] Somehow failed to transfer NidoranFemale with 231 CP. ReleasePokemonOutProto.Status was 3`

**Comment by shiftcodeYT** [comment]
@plum04 that's normal, i'll implement a transferall soon. @Epsilith that really seems like a bug, does it only happen with nidoranFemale or with every pokemon, and how often did it happen?

**Comment by Teem85** [comment]
doesnt transfer Pinsir too, just collects them until the box is full seem like there is no iv check too

**Comment by plum04** [comment]
Are you aware of all the ones that don't have transfer implemented yet, or would a list possibly be helpful?

**Comment by Epsilith** [comment]
@shiftcodeYT Everytime it tries to transfer NidoranFemale it will say it is then give the aforementioned error.

**Comment by shiftcodeYT** [comment]
Fixed in 3.0
