### ISSUE TITLE
Specific Pokemon Evolution/transfer feature

### ISSUE THREAD

**Issue by kingkong91108** [shiftcodeYT/PokeBot3#45]
Is it possible to implement a feature that specifically chooses one type of pokemon and evolve it? For example if i had 630 pidgey candies and i only want to evolve all the pidgeys in my backpack i can just use the evolve farming pokemon feature. And instead of
 "EvolveAllGivenPokemons" we can do
 "EvolveExpFarmingPokemons" and for the list of farming pokemons we can have weedles and pidgeys and other cheap to evolve pokemons. The current evolution bot makes me evolve pidgeottos sometimes and that takes way more candies and gives fewer exp.

**Comment by shiftcodeYT** [comment]
Great Idea!

**Comment by shiftcodeYT** [comment]
Done in 3.0
