### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by shiftcodeYT** [shiftcodeYT/PokeBot3#5]
Request features here ;)

**Comment by kingsofcoms** [comment]
Could you explain how far it farms from the main coordinate. Does it only farm pokemons that are around pokestops or the entire map?

Feature request:
1. Ability to set IVs percentage, say 85%, everything below will be transferred.
2. Implement walking and walking speed.
3. Implement seperate farming modes:
a. XP Mode: visits pokestops only (might farm pokemons that may spawn near pokestops)
b. Stardust Mode: Walks/Scans a large radius from given coordinates for pokemons, keeps repeating.

**Comment by shiftcodeYT** [comment]
0) it farms in 30m radius or so
1) i'll definitely implement that :)
2) Walking is already implemented
3) Awesome idea :) Looking forward to that on my own.

**Comment by kingsofcoms** [comment]
Awesome :+1:

**Comment by houmik** [comment]
Hi, i dont like the percentage feature. I have too much pokemons and i want to have only strongest ones... How i can change it?

**Comment by shiftcodeYT** [comment]
@houmik change transfertype to duplicate

**Comment by Akayso** [comment]
Option to catch and keep specific pokemon (set bot to catch 20 pidgey's, keep 20 pidgey's etc)
Option to evolve specific pokemon, and the number of evolutions the bot should do for it.

**Comment by Akayso** [comment]
Option to use specific pokeballs for specific pokemon i.e use Greatball when T2 pokemon or CP over 300?
Ultraball for every max tier pokemon and/or over 1000 CP first evolution

**Comment by houmik** [comment]
Option for transfertype duplicate to have like XY best pokemons of that type ( like if i set it to 3 i always have 3 Pidgeys, 3 Machokes etc ... )

**Comment by Smilhjan** [comment]
maybe a version for mac? tried it on friends pc, working great. but sadly, at home i can't use it

**Comment by cyberguy91** [comment]
Hi. I tried this on my main account, which has 600 spots in backpack and lost most of my potions and revives due to me not understanding what the recycle was doing. Is there a way to turn recycling of? I set the recycle interval to 9999999999999999999 but once it said no usable locations wait 10 seconds, it recycled anyway.

**Comment by shiftcodeYT** [comment]
I'm going to add a disable recycle setting in next release.

**Comment by xeriix** [comment]
farm pokstop and catch pokemons dosnt work for me in my old acc any help?

**Comment by spot88** [comment]
Need more info, and please create a own issue.

**Comment by pokemonbotter** [comment]
I would love an option to farm at different locations

Something easy just imput X cor and farm there

**Comment by shiftcodeYT** [comment]
Everything added in 3.0
