### ISSUE TITLE
Evolve function (exclude/only evolve Max CP)

### ISSUE THREAD

**Issue by theoneandonly81** [shiftcodeYT/PokeBot3#62]
Could we add the possibility to exclude certain Pokemons from auto evolving?

Additionally I would recommend to always evolve the highest CP Pokemon. It currently doesn't take the highest CP Pokemon.. it evolved a 70 CP magikorp instead of a 185 CP magicorp.. :(

**Comment by houmik** [comment]
This would be nice but .... 1805 magikarp ? da fuck you smoking

**Comment by Pepsai** [comment]
Yeah agreed. That would be nice. I thought the max of magikarp was something under 300 CP.

**Comment by theoneandonly81** [comment]
typo my bad. 185 CP magikorp appologies.

**Comment by Pepsai** [comment]
I have been looking through the config file, if you have leavestrongest on it should evolve the best you have because there is only one pokemon of the type to evolve because it transfers all the worst once.

**Comment by houmik** [comment]
Actually you need to set it as Duplicate. Leave strongest transfering pokemons under 80%. So you can get like 10 magikarps if they are above 80%.

**Comment by shiftcodeYT** [comment]
Done in 3.0
