### ISSUE TITLE
LeaveStrongest transfer settings. 

### ISSUE THREAD

**Issue by kingkong91108** [shiftcodeYT/PokeBot3#72]
How do i change the iv percentage to 95%?. Also the leave strongest doesnt work with evolutions of some pokemons that have been captured with really low cp

**Comment by Pepsai** [comment]
I have the same problem. Leavestrongest does not transfer evolved pokemon.
This results in me having a crazy amount of rattatas and other pokemon, but this is the one i have the most of. I would really like this to be fixed even though it might be hard.
https://gyazo.com/730c6708e8b6652c09fde168ca82e60f

Thanks a lot for your amazing works developers!

**Comment by Doodil** [comment]
Hey, I don't think this is a bug, but a misinterpretation of the name of the setting. If you look in the "AllButStrongestTransferStrategy.cs" you will see that it only transfers a certain list of unwanted pokemon, mainly pidgeys, rattatas, weedle, zubat, etc. This list does not contain any of the evolved forms. What you want is the "duplicate" strategy, which sends away all pokemon that are duplicates, and only keeps the strongest.

**Comment by Pepsai** [comment]
Yeah i figured this out yesterday while looking at the code over at Pokemon-Go-Rocket-API

Thanks a lot for clearing it up though!

**Comment by shiftcodeYT** [comment]
Done in 3.0
