### ISSUE TITLE
Possible Softban Unban Feature

### ISSUE THREAD

**Issue by svvperb** [shiftcodeYT/PokeBot3#83]
There is a possible technical bug fix for unbanning 'soft-banned' users. Maybe this could be implemented if resources and time are available. Basically, if you spin a nearby pokestop 40 times, you'll be unbanned, benefitting users who gradually spoof locations.

Source - https://www.youtube.com/watch?v=_N_60Dsgwok
Thank you for all your hard work shiftcodeYT. Can't wait for a GUI release.

**Comment by svvperb** [comment]
If you need any assistance in designing user/experience interface elements, feel free to reach out.

**Comment by shiftcodeYT** [comment]
Wow. Honestly didn't believe this. I'll try :)

**Comment by shiftcodeYT** [comment]
@svvperb Use QuickSpin! http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/565264-quickspin-pokemongo-softban-unbanner-quickly-unbans-your-softbanned-account.html
