### ISSUE TITLE
For the evolution request again

### ISSUE THREAD

**Issue by Luc4z** [shiftcodeYT/PokeBot3#9]
_**and if there's a XP mode in the futer , it should also capture pokemon too because with candy it can gain more exp .**_ 

also can you add evolve all pokemon in "leaveStrongest" list before transfer them ?
or just make a list for evolethemall .

about evolution i means if you capture one and before you transfer it , if you got enough candy then evolve first and transfer later , i don't think its useless tho , if you don't put that pokemon into "evolve transfer list"(or other after @shiftcodeYT made) , its fine .

just imagine whats different between extra 500 exp after you caught 5 pidgey .
and i also know some guys might ask why dont i just do it myself becuase ? it because after 2 days botting , i got 400+ candies for pidgey .. 100 times evole ? senpai i need bot do it for me ! 

**and also for example , pidgey only need 15 candies to evolve and it will gain 500 exp**

**Comment by Luc4z** [comment]
and also as the other guy here said "but doesn't evolve cost around 50 candies for some pokemons, thats a lot. Those candies could be used to powerup better IV pokemons though." , its easy , don't put that one in evolve list

**Comment by shiftcodeYT** [comment]
O.K., I'm dumb. Just a priority problem. I'll fix that tomorrow or so. :)

Note for me: `switch Evolve and transfer in Program.cs`

**Comment by kingsofcoms** [comment]
@Luc4z I get you dilemma to evolve pidgeys. Agreed it should be in a allowall/addexception list coz you don't want to evolve all pokemons.

**Comment by shiftcodeYT** [comment]
I'm simply going to get all lists into the config file. Then everyone is happy :)

**Comment by Luc4z** [comment]
hope it can be done soon , its Neer made it happened now , but it has walk to pokestop way tooooo slow for botting , hope you can take a look at his stuff，he called it PokeFast https://mega.nz/#!7VJA2CKZ!MJHNZ0ljZM1cX0bQ8GJze0-sUwSrZOQZ0UIE-ORmRa8 ，capture pokemons is really fast but walk to pokestop is so dumb , took over 10 secodons each

**Comment by Luc4z** [comment]
and this one , he got that perfect feature , evolve first before transfer https://github.com/Spegeli/Pokemon-Go-Rocket-API

**Comment by shiftcodeYT** [comment]
Done in 3.0
