### ISSUE TITLE
[Bot Broken ATM] [Working on a fix]

### ISSUE THREAD

**Issue by shiftcodeYT** [shiftcodeYT/PokeBot3#93]
I know it doesn't work ATM(at least for google. PTC: idk). I'm a 14-year-old student and was on a holiday camp for a week. I'm back now and doing everything in order to fix it. [Thanks].
Please don't create issues about this, just comment here.

**Comment by PremeTeam** [comment]
Yeah google not working. Just keep getting an exception error. No problem take your time, thanks for your hard work.

**Comment by NurdinA** [comment]
Thank you very much , is waiting for release

**Comment by shiftcodeYT** [comment]
Done. Download 3.0 and follow Instructions in readme.md
