### ISSUE TITLE
How do i run this precompiled bot?

### ISSUE THREAD

**Issue by kingkong91108** [shiftcodeYT/PokeBot3#95]
The instructions says to download and extract and change settings to liking but i dont see where i can change the settings or run the bot. It seems like i have to build it first

**Comment by houmik** [comment]
Download 3.0 here ( https://github.com/shiftcodeYT/PokeBot3/releases ) and extract it somewhere. 
Then just open PokemonGo.RocketAPI.Console.exe

**Comment by shiftcodeYT** [comment]
@houmik thanks.
