### ISSUE TITLE
Feature request - Pokemon priority

### ISSUE THREAD

**Issue by houmik** [shiftcodeYT/PokeBot3#96]
Hi you did a really great job with 3.0 and i want to thank you for your hard work.

Lets talk about feature. I saw u using PokeVision and your bot know where is pokestops and pokemons. Can you add something like Pokemon priority list ? When Bot see pokemon on this list, its going to ignore everything ( Pokestops or pokemons in range ) and just go to catch the one with priority, It will be really great for catching Dratini, Snorlax or other rare pokemons.

Sorry for my bad English :)

**Comment by shiftcodeYT** [comment]
That's a great Idea! I'll look into it in the next few days.

**Comment by houmik** [comment]
And it would be nice to have Range setting for this ...
Also i see PokeVision is down right now ... i found [this](https://jz6.github.io/PoGoMap/) but i didnt test it yet

**Comment by shiftcodeYT** [comment]
Checked through the code, not worth the effort
