### ISSUE TITLE
google acc with pokebot3

### ISSUE THREAD

**Issue by cokelight** [shiftcodeYT/PokeBot3#97]
i have some problems with my google acc.... after started the exe file and setting ..all i see is that
![cattura](https://cloud.githubusercontent.com/assets/20746305/17273476/e1de1202-56b5-11e6-9266-e4aa7a0714a8.PNG)

...what i have to do?

**Comment by FallenDev** [comment]
Says bad authentication, so either your username or password was incorrect. Fix that, and it should work.

**Comment by cokelight** [comment]
im sure user and pass are correct.

**Comment by FallenDev** [comment]
Strange, check your settings file just in case. Also go to google and login. There was also an update today for the game. Download that and then login and see if you're able to.

**Comment by FallenDev** [comment]
If you're able to login in both google and poke'mon Go. Then there might be a problem somewhere in the app for you. I'd recommend saving your settings files and redownloading the newest version.

**Comment by cokelight** [comment]
i checked all the setting again as you told me but nothing changed.so i created an ptc and tried with it and this time worked.i dont understand why. when will the newest app's version be released?

**Comment by shiftcodeYT** [comment]
BadAuthentication = Wrong username/password. Nothing else.
