### ISSUE TITLE
Is it just me

### ISSUE THREAD

**Issue by AetherAeolus** [shiftcodeYT/PokeBot3#99]
I don't know what i'm doing wrong but pokemon aint transfering. Also anyway to sort pokemon by pokemon number?

**Comment by FallenDev** [comment]
Transfer was one of the things updated in the new update. Since that was changed and transfer button was made into a combobox it'll have to be updated in the code.

**Comment by shiftcodeYT** [comment]
Transfer works for me.
[img](http://i.imgur.com/2TUfQSd.png)
